/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminArendenRouteImport } from './routes/_authenticated/admin.arenden'
import { Route as AuthenticatedAdminBoendeRouteImport } from './routes/_authenticated/admin.boende'
import { Route as AuthenticatedAdminBokningarRouteImport } from './routes/_authenticated/admin.bokningar'
import { Route as AuthenticatedAdminEkonomiRouteImport } from './routes/_authenticated/admin.ekonomi'
import { Route as AuthenticatedAdminEntreprenorerRouteImport } from './routes/_authenticated/admin.entreprenorer'
import { Route as AuthenticatedAdminFastigheterRouteImport } from './routes/_authenticated/admin.fastigheter'
import { Route as AuthenticatedAdminInstallningarRouteImport } from './routes/_authenticated/admin.installningar'
import { Route as AuthenticatedAdminKommunikationRouteImport } from './routes/_authenticated/admin.kommunikation'
import { Route as AuthenticatedAdminUnderhallRouteImport } from './routes/_authenticated/admin.underhall'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppBoendeRouteImport } from './routes/_authenticated/app.boende'
import { Route as AuthenticatedAppBokningarRouteImport } from './routes/_authenticated/app.bokningar'
import { Route as AuthenticatedAppDokumentRouteImport } from './routes/_authenticated/app.dokument'
import { Route as AuthenticatedAppEkonomiRouteImport } from './routes/_authenticated/app.ekonomi'
import { Route as AuthenticatedAppFelanmalanRouteImport } from './routes/_authenticated/app.felanmalan'
import { Route as AuthenticatedAppInformationRouteImport } from './routes/_authenticated/app.information'
import { Route as AuthenticatedAppMeddelandenRouteImport } from './routes/_authenticated/app.meddelanden'
import { Route as AuthenticatedAppMotenRouteImport } from './routes/_authenticated/app.moten'
import { Route as AuthenticatedAdminArendenIdRouteImport } from './routes/_authenticated/admin.arenden.$id'
import { Route as AuthenticatedAdminBoendeIdRouteImport } from './routes/_authenticated/admin.boende.$id'
import { Route as AuthenticatedAppFelanmalanIdRouteImport } from './routes/_authenticated/app.felanmalan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminArendenRoute =
  AuthenticatedAdminArendenRouteImport.update({
    id: '/arenden',
    path: '/arenden',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBoendeRoute =
  AuthenticatedAdminBoendeRouteImport.update({
    id: '/boende',
    path: '/boende',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBokningarRoute =
  AuthenticatedAdminBokningarRouteImport.update({
    id: '/bokningar',
    path: '/bokningar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEkonomiRoute =
  AuthenticatedAdminEkonomiRouteImport.update({
    id: '/ekonomi',
    path: '/ekonomi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEntreprenorerRoute =
  AuthenticatedAdminEntreprenorerRouteImport.update({
    id: '/entreprenorer',
    path: '/entreprenorer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFastigheterRoute =
  AuthenticatedAdminFastigheterRouteImport.update({
    id: '/fastigheter',
    path: '/fastigheter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstallningarRoute =
  AuthenticatedAdminInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKommunikationRoute =
  AuthenticatedAdminKommunikationRouteImport.update({
    id: '/kommunikation',
    path: '/kommunikation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUnderhallRoute =
  AuthenticatedAdminUnderhallRouteImport.update({
    id: '/underhall',
    path: '/underhall',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBoendeRoute = AuthenticatedAppBoendeRouteImport.update({
  id: '/boende',
  path: '/boende',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBokningarRoute =
  AuthenticatedAppBokningarRouteImport.update({
    id: '/bokningar',
    path: '/bokningar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDokumentRoute =
  AuthenticatedAppDokumentRouteImport.update({
    id: '/dokument',
    path: '/dokument',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEkonomiRoute = AuthenticatedAppEkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFelanmalanRoute =
  AuthenticatedAppFelanmalanRouteImport.update({
    id: '/felanmalan',
    path: '/felanmalan',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInformationRoute =
  AuthenticatedAppInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMeddelandenRoute =
  AuthenticatedAppMeddelandenRouteImport.update({
    id: '/meddelanden',
    path: '/meddelanden',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMotenRoute = AuthenticatedAppMotenRouteImport.update({
  id: '/moten',
  path: '/moten',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminArendenIdRoute =
  AuthenticatedAdminArendenIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminArendenRoute,
  } as any)
const AuthenticatedAdminBoendeIdRoute =
  AuthenticatedAdminBoendeIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBoendeRoute,
  } as any)
const AuthenticatedAppFelanmalanIdRoute =
  AuthenticatedAppFelanmalanIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppFelanmalanRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/arenden': typeof AuthenticatedAdminArendenRouteWithChildren
  '/admin/boende': typeof AuthenticatedAdminBoendeRouteWithChildren
  '/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/app/boende': typeof AuthenticatedAppBoendeRoute
  '/app/bokningar': typeof AuthenticatedAppBokningarRoute
  '/app/dokument': typeof AuthenticatedAppDokumentRoute
  '/app/ekonomi': typeof AuthenticatedAppEkonomiRoute
  '/app/felanmalan': typeof AuthenticatedAppFelanmalanRouteWithChildren
  '/app/information': typeof AuthenticatedAppInformationRoute
  '/app/meddelanden': typeof AuthenticatedAppMeddelandenRoute
  '/app/moten': typeof AuthenticatedAppMotenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
  '/app/felanmalan/$id': typeof AuthenticatedAppFelanmalanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/arenden': typeof AuthenticatedAdminArendenRouteWithChildren
  '/admin/boende': typeof AuthenticatedAdminBoendeRouteWithChildren
  '/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/app/boende': typeof AuthenticatedAppBoendeRoute
  '/app/bokningar': typeof AuthenticatedAppBokningarRoute
  '/app/dokument': typeof AuthenticatedAppDokumentRoute
  '/app/ekonomi': typeof AuthenticatedAppEkonomiRoute
  '/app/felanmalan': typeof AuthenticatedAppFelanmalanRouteWithChildren
  '/app/information': typeof AuthenticatedAppInformationRoute
  '/app/meddelanden': typeof AuthenticatedAppMeddelandenRoute
  '/app/moten': typeof AuthenticatedAppMotenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
  '/app/felanmalan/$id': typeof AuthenticatedAppFelanmalanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/arenden': typeof AuthenticatedAdminArendenRouteWithChildren
  '/_authenticated/admin/boende': typeof AuthenticatedAdminBoendeRouteWithChildren
  '/_authenticated/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/_authenticated/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/_authenticated/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/_authenticated/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/_authenticated/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/_authenticated/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/_authenticated/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/_authenticated/app/boende': typeof AuthenticatedAppBoendeRoute
  '/_authenticated/app/bokningar': typeof AuthenticatedAppBokningarRoute
  '/_authenticated/app/dokument': typeof AuthenticatedAppDokumentRoute
  '/_authenticated/app/ekonomi': typeof AuthenticatedAppEkonomiRoute
  '/_authenticated/app/felanmalan': typeof AuthenticatedAppFelanmalanRouteWithChildren
  '/_authenticated/app/information': typeof AuthenticatedAppInformationRoute
  '/_authenticated/app/meddelanden': typeof AuthenticatedAppMeddelandenRoute
  '/_authenticated/app/moten': typeof AuthenticatedAppMotenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/_authenticated/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
  '/_authenticated/app/felanmalan/$id': typeof AuthenticatedAppFelanmalanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/admin/arenden'
    | '/admin/boende'
    | '/admin/bokningar'
    | '/admin/ekonomi'
    | '/admin/entreprenorer'
    | '/admin/fastigheter'
    | '/admin/installningar'
    | '/admin/kommunikation'
    | '/admin/underhall'
    | '/app/boende'
    | '/app/bokningar'
    | '/app/dokument'
    | '/app/ekonomi'
    | '/app/felanmalan'
    | '/app/information'
    | '/app/meddelanden'
    | '/app/moten'
    | '/admin/'
    | '/app/'
    | '/admin/arenden/$id'
    | '/admin/boende/$id'
    | '/app/felanmalan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/arenden'
    | '/admin/boende'
    | '/admin/bokningar'
    | '/admin/ekonomi'
    | '/admin/entreprenorer'
    | '/admin/fastigheter'
    | '/admin/installningar'
    | '/admin/kommunikation'
    | '/admin/underhall'
    | '/app/boende'
    | '/app/bokningar'
    | '/app/dokument'
    | '/app/ekonomi'
    | '/app/felanmalan'
    | '/app/information'
    | '/app/meddelanden'
    | '/app/moten'
    | '/admin'
    | '/app'
    | '/admin/arenden/$id'
    | '/admin/boende/$id'
    | '/app/felanmalan/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/arenden'
    | '/_authenticated/admin/boende'
    | '/_authenticated/admin/bokningar'
    | '/_authenticated/admin/ekonomi'
    | '/_authenticated/admin/entreprenorer'
    | '/_authenticated/admin/fastigheter'
    | '/_authenticated/admin/installningar'
    | '/_authenticated/admin/kommunikation'
    | '/_authenticated/admin/underhall'
    | '/_authenticated/app/boende'
    | '/_authenticated/app/bokningar'
    | '/_authenticated/app/dokument'
    | '/_authenticated/app/ekonomi'
    | '/_authenticated/app/felanmalan'
    | '/_authenticated/app/information'
    | '/_authenticated/app/meddelanden'
    | '/_authenticated/app/moten'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/arenden/$id'
    | '/_authenticated/admin/boende/$id'
    | '/_authenticated/app/felanmalan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/arenden': {
      id: '/_authenticated/admin/arenden'
      path: '/arenden'
      fullPath: '/admin/arenden'
      preLoaderRoute: typeof AuthenticatedAdminArendenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/boende': {
      id: '/_authenticated/admin/boende'
      path: '/boende'
      fullPath: '/admin/boende'
      preLoaderRoute: typeof AuthenticatedAdminBoendeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bokningar': {
      id: '/_authenticated/admin/bokningar'
      path: '/bokningar'
      fullPath: '/admin/bokningar'
      preLoaderRoute: typeof AuthenticatedAdminBokningarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ekonomi': {
      id: '/_authenticated/admin/ekonomi'
      path: '/ekonomi'
      fullPath: '/admin/ekonomi'
      preLoaderRoute: typeof AuthenticatedAdminEkonomiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/entreprenorer': {
      id: '/_authenticated/admin/entreprenorer'
      path: '/entreprenorer'
      fullPath: '/admin/entreprenorer'
      preLoaderRoute: typeof AuthenticatedAdminEntreprenorerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fastigheter': {
      id: '/_authenticated/admin/fastigheter'
      path: '/fastigheter'
      fullPath: '/admin/fastigheter'
      preLoaderRoute: typeof AuthenticatedAdminFastigheterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/installningar': {
      id: '/_authenticated/admin/installningar'
      path: '/installningar'
      fullPath: '/admin/installningar'
      preLoaderRoute: typeof AuthenticatedAdminInstallningarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kommunikation': {
      id: '/_authenticated/admin/kommunikation'
      path: '/kommunikation'
      fullPath: '/admin/kommunikation'
      preLoaderRoute: typeof AuthenticatedAdminKommunikationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/underhall': {
      id: '/_authenticated/admin/underhall'
      path: '/underhall'
      fullPath: '/admin/underhall'
      preLoaderRoute: typeof AuthenticatedAdminUnderhallRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/boende': {
      id: '/_authenticated/app/boende'
      path: '/boende'
      fullPath: '/app/boende'
      preLoaderRoute: typeof AuthenticatedAppBoendeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bokningar': {
      id: '/_authenticated/app/bokningar'
      path: '/bokningar'
      fullPath: '/app/bokningar'
      preLoaderRoute: typeof AuthenticatedAppBokningarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dokument': {
      id: '/_authenticated/app/dokument'
      path: '/dokument'
      fullPath: '/app/dokument'
      preLoaderRoute: typeof AuthenticatedAppDokumentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ekonomi': {
      id: '/_authenticated/app/ekonomi'
      path: '/ekonomi'
      fullPath: '/app/ekonomi'
      preLoaderRoute: typeof AuthenticatedAppEkonomiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/felanmalan': {
      id: '/_authenticated/app/felanmalan'
      path: '/felanmalan'
      fullPath: '/app/felanmalan'
      preLoaderRoute: typeof AuthenticatedAppFelanmalanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/information': {
      id: '/_authenticated/app/information'
      path: '/information'
      fullPath: '/app/information'
      preLoaderRoute: typeof AuthenticatedAppInformationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/meddelanden': {
      id: '/_authenticated/app/meddelanden'
      path: '/meddelanden'
      fullPath: '/app/meddelanden'
      preLoaderRoute: typeof AuthenticatedAppMeddelandenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/moten': {
      id: '/_authenticated/app/moten'
      path: '/moten'
      fullPath: '/app/moten'
      preLoaderRoute: typeof AuthenticatedAppMotenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/arenden/$id': {
      id: '/_authenticated/admin/arenden/$id'
      path: '/$id'
      fullPath: '/admin/arenden/$id'
      preLoaderRoute: typeof AuthenticatedAdminArendenIdRouteImport
      parentRoute: typeof AuthenticatedAdminArendenRoute
    }
    '/_authenticated/admin/boende/$id': {
      id: '/_authenticated/admin/boende/$id'
      path: '/$id'
      fullPath: '/admin/boende/$id'
      preLoaderRoute: typeof AuthenticatedAdminBoendeIdRouteImport
      parentRoute: typeof AuthenticatedAdminBoendeRoute
    }
    '/_authenticated/app/felanmalan/$id': {
      id: '/_authenticated/app/felanmalan/$id'
      path: '/$id'
      fullPath: '/app/felanmalan/$id'
      preLoaderRoute: typeof AuthenticatedAppFelanmalanIdRouteImport
      parentRoute: typeof AuthenticatedAppFelanmalanRoute
    }
  }
}

interface AuthenticatedAdminArendenRouteChildren {
  AuthenticatedAdminArendenIdRoute: typeof AuthenticatedAdminArendenIdRoute
}

const AuthenticatedAdminArendenRouteChildren: AuthenticatedAdminArendenRouteChildren =
  {
    AuthenticatedAdminArendenIdRoute: AuthenticatedAdminArendenIdRoute,
  }

const AuthenticatedAdminArendenRouteWithChildren =
  AuthenticatedAdminArendenRoute._addFileChildren(
    AuthenticatedAdminArendenRouteChildren,
  )

interface AuthenticatedAdminBoendeRouteChildren {
  AuthenticatedAdminBoendeIdRoute: typeof AuthenticatedAdminBoendeIdRoute
}

const AuthenticatedAdminBoendeRouteChildren: AuthenticatedAdminBoendeRouteChildren =
  {
    AuthenticatedAdminBoendeIdRoute: AuthenticatedAdminBoendeIdRoute,
  }

const AuthenticatedAdminBoendeRouteWithChildren =
  AuthenticatedAdminBoendeRoute._addFileChildren(
    AuthenticatedAdminBoendeRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminArendenRoute: typeof AuthenticatedAdminArendenRouteWithChildren
  AuthenticatedAdminBoendeRoute: typeof AuthenticatedAdminBoendeRouteWithChildren
  AuthenticatedAdminBokningarRoute: typeof AuthenticatedAdminBokningarRoute
  AuthenticatedAdminEkonomiRoute: typeof AuthenticatedAdminEkonomiRoute
  AuthenticatedAdminEntreprenorerRoute: typeof AuthenticatedAdminEntreprenorerRoute
  AuthenticatedAdminFastigheterRoute: typeof AuthenticatedAdminFastigheterRoute
  AuthenticatedAdminInstallningarRoute: typeof AuthenticatedAdminInstallningarRoute
  AuthenticatedAdminKommunikationRoute: typeof AuthenticatedAdminKommunikationRoute
  AuthenticatedAdminUnderhallRoute: typeof AuthenticatedAdminUnderhallRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminArendenRoute: AuthenticatedAdminArendenRouteWithChildren,
  AuthenticatedAdminBoendeRoute: AuthenticatedAdminBoendeRouteWithChildren,
  AuthenticatedAdminBokningarRoute: AuthenticatedAdminBokningarRoute,
  AuthenticatedAdminEkonomiRoute: AuthenticatedAdminEkonomiRoute,
  AuthenticatedAdminEntreprenorerRoute: AuthenticatedAdminEntreprenorerRoute,
  AuthenticatedAdminFastigheterRoute: AuthenticatedAdminFastigheterRoute,
  AuthenticatedAdminInstallningarRoute: AuthenticatedAdminInstallningarRoute,
  AuthenticatedAdminKommunikationRoute: AuthenticatedAdminKommunikationRoute,
  AuthenticatedAdminUnderhallRoute: AuthenticatedAdminUnderhallRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppFelanmalanRouteChildren {
  AuthenticatedAppFelanmalanIdRoute: typeof AuthenticatedAppFelanmalanIdRoute
}

const AuthenticatedAppFelanmalanRouteChildren: AuthenticatedAppFelanmalanRouteChildren =
  {
    AuthenticatedAppFelanmalanIdRoute: AuthenticatedAppFelanmalanIdRoute,
  }

const AuthenticatedAppFelanmalanRouteWithChildren =
  AuthenticatedAppFelanmalanRoute._addFileChildren(
    AuthenticatedAppFelanmalanRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBoendeRoute: typeof AuthenticatedAppBoendeRoute
  AuthenticatedAppBokningarRoute: typeof AuthenticatedAppBokningarRoute
  AuthenticatedAppDokumentRoute: typeof AuthenticatedAppDokumentRoute
  AuthenticatedAppEkonomiRoute: typeof AuthenticatedAppEkonomiRoute
  AuthenticatedAppFelanmalanRoute: typeof AuthenticatedAppFelanmalanRouteWithChildren
  AuthenticatedAppInformationRoute: typeof AuthenticatedAppInformationRoute
  AuthenticatedAppMeddelandenRoute: typeof AuthenticatedAppMeddelandenRoute
  AuthenticatedAppMotenRoute: typeof AuthenticatedAppMotenRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBoendeRoute: AuthenticatedAppBoendeRoute,
  AuthenticatedAppBokningarRoute: AuthenticatedAppBokningarRoute,
  AuthenticatedAppDokumentRoute: AuthenticatedAppDokumentRoute,
  AuthenticatedAppEkonomiRoute: AuthenticatedAppEkonomiRoute,
  AuthenticatedAppFelanmalanRoute: AuthenticatedAppFelanmalanRouteWithChildren,
  AuthenticatedAppInformationRoute: AuthenticatedAppInformationRoute,
  AuthenticatedAppMeddelandenRoute: AuthenticatedAppMeddelandenRoute,
  AuthenticatedAppMotenRoute: AuthenticatedAppMotenRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
