/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BokaDemoRouteImport } from './routes/boka-demo'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedEntreprenorRouteImport } from './routes/_authenticated/entreprenor'
import { Route as AuthAterstallRouteImport } from './routes/auth_.aterstall'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAbonnemangRouteImport } from './routes/_authenticated/admin.abonnemang'
import { Route as AuthenticatedAdminBesiktningarRouteImport } from './routes/_authenticated/admin.besiktningar'
import { Route as AuthenticatedAdminBokningarRouteImport } from './routes/_authenticated/admin.bokningar'
import { Route as AuthenticatedAdminDokumentRouteImport } from './routes/_authenticated/admin.dokument'
import { Route as AuthenticatedAdminEkonomiRouteImport } from './routes/_authenticated/admin.ekonomi'
import { Route as AuthenticatedAdminEntreprenorerRouteImport } from './routes/_authenticated/admin.entreprenorer'
import { Route as AuthenticatedAdminFastigheterRouteImport } from './routes/_authenticated/admin.fastigheter'
import { Route as AuthenticatedAdminInstallningarRouteImport } from './routes/_authenticated/admin.installningar'
import { Route as AuthenticatedAdminKommunikationRouteImport } from './routes/_authenticated/admin.kommunikation'
import { Route as AuthenticatedAdminMeddelandenRouteImport } from './routes/_authenticated/admin.meddelanden'
import { Route as AuthenticatedAdminMotenRouteImport } from './routes/_authenticated/admin.moten'
import { Route as AuthenticatedAdminPassersystemRouteImport } from './routes/_authenticated/admin.passersystem'
import { Route as AuthenticatedAdminUnderhallRouteImport } from './routes/_authenticated/admin.underhall'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppBoendeRouteImport } from './routes/_authenticated/app.boende'
import { Route as AuthenticatedAppBokningarRouteImport } from './routes/_authenticated/app.bokningar'
import { Route as AuthenticatedAppDokumentRouteImport } from './routes/_authenticated/app.dokument'
import { Route as AuthenticatedAppEkonomiRouteImport } from './routes/_authenticated/app.ekonomi'
import { Route as AuthenticatedAppInformationRouteImport } from './routes/_authenticated/app.information'
import { Route as AuthenticatedAppMeddelandenRouteImport } from './routes/_authenticated/app.meddelanden'
import { Route as AuthenticatedAppMotenRouteImport } from './routes/_authenticated/app.moten'
import { Route as AuthenticatedAppNycklarRouteImport } from './routes/_authenticated/app.nycklar'
import { Route as AuthenticatedEntreprenorIndexRouteImport } from './routes/_authenticated/entreprenor.index'
import { Route as AuthenticatedEntreprenorIdRouteImport } from './routes/_authenticated/entreprenor.$id'
import { Route as AuthenticatedNDoorIdRouteImport } from './routes/_authenticated/n.$doorId'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as AuthenticatedAdminArendenIndexRouteImport } from './routes/_authenticated/admin.arenden.index'
import { Route as AuthenticatedAdminArendenIdRouteImport } from './routes/_authenticated/admin.arenden.$id'
import { Route as AuthenticatedAdminBoendeIndexRouteImport } from './routes/_authenticated/admin.boende.index'
import { Route as AuthenticatedAdminBoendeIdRouteImport } from './routes/_authenticated/admin.boende.$id'
import { Route as AuthenticatedAppFelanmalanIndexRouteImport } from './routes/_authenticated/app.felanmalan.index'
import { Route as AuthenticatedAppFelanmalanIdRouteImport } from './routes/_authenticated/app.felanmalan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BokaDemoRoute = BokaDemoRouteImport.update({
  id: '/boka-demo',
  path: '/boka-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntreprenorRoute =
  AuthenticatedEntreprenorRouteImport.update({
    id: '/entreprenor',
    path: '/entreprenor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthAterstallRoute = AuthAterstallRouteImport.update({
  id: '/auth_/aterstall',
  path: '/auth/aterstall',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAbonnemangRoute =
  AuthenticatedAdminAbonnemangRouteImport.update({
    id: '/abonnemang',
    path: '/abonnemang',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBesiktningarRoute =
  AuthenticatedAdminBesiktningarRouteImport.update({
    id: '/besiktningar',
    path: '/besiktningar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBokningarRoute =
  AuthenticatedAdminBokningarRouteImport.update({
    id: '/bokningar',
    path: '/bokningar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDokumentRoute =
  AuthenticatedAdminDokumentRouteImport.update({
    id: '/dokument',
    path: '/dokument',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEkonomiRoute =
  AuthenticatedAdminEkonomiRouteImport.update({
    id: '/ekonomi',
    path: '/ekonomi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEntreprenorerRoute =
  AuthenticatedAdminEntreprenorerRouteImport.update({
    id: '/entreprenorer',
    path: '/entreprenorer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFastigheterRoute =
  AuthenticatedAdminFastigheterRouteImport.update({
    id: '/fastigheter',
    path: '/fastigheter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstallningarRoute =
  AuthenticatedAdminInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKommunikationRoute =
  AuthenticatedAdminKommunikationRouteImport.update({
    id: '/kommunikation',
    path: '/kommunikation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMeddelandenRoute =
  AuthenticatedAdminMeddelandenRouteImport.update({
    id: '/meddelanden',
    path: '/meddelanden',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMotenRoute = AuthenticatedAdminMotenRouteImport.update({
  id: '/moten',
  path: '/moten',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPassersystemRoute =
  AuthenticatedAdminPassersystemRouteImport.update({
    id: '/passersystem',
    path: '/passersystem',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUnderhallRoute =
  AuthenticatedAdminUnderhallRouteImport.update({
    id: '/underhall',
    path: '/underhall',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBoendeRoute = AuthenticatedAppBoendeRouteImport.update({
  id: '/boende',
  path: '/boende',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBokningarRoute =
  AuthenticatedAppBokningarRouteImport.update({
    id: '/bokningar',
    path: '/bokningar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDokumentRoute =
  AuthenticatedAppDokumentRouteImport.update({
    id: '/dokument',
    path: '/dokument',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEkonomiRoute = AuthenticatedAppEkonomiRouteImport.update({
  id: '/ekonomi',
  path: '/ekonomi',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInformationRoute =
  AuthenticatedAppInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMeddelandenRoute =
  AuthenticatedAppMeddelandenRouteImport.update({
    id: '/meddelanden',
    path: '/meddelanden',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMotenRoute = AuthenticatedAppMotenRouteImport.update({
  id: '/moten',
  path: '/moten',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNycklarRoute = AuthenticatedAppNycklarRouteImport.update({
  id: '/nycklar',
  path: '/nycklar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedEntreprenorIndexRoute =
  AuthenticatedEntreprenorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntreprenorRoute,
  } as any)
const AuthenticatedEntreprenorIdRoute =
  AuthenticatedEntreprenorIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedEntreprenorRoute,
  } as any)
const AuthenticatedNDoorIdRoute = AuthenticatedNDoorIdRouteImport.update({
  id: '/n/$doorId',
  path: '/n/$doorId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminArendenIndexRoute =
  AuthenticatedAdminArendenIndexRouteImport.update({
    id: '/arenden/',
    path: '/arenden/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminArendenIdRoute =
  AuthenticatedAdminArendenIdRouteImport.update({
    id: '/arenden/$id',
    path: '/arenden/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBoendeIndexRoute =
  AuthenticatedAdminBoendeIndexRouteImport.update({
    id: '/boende/',
    path: '/boende/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBoendeIdRoute =
  AuthenticatedAdminBoendeIdRouteImport.update({
    id: '/boende/$id',
    path: '/boende/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppFelanmalanIndexRoute =
  AuthenticatedAppFelanmalanIndexRouteImport.update({
    id: '/felanmalan/',
    path: '/felanmalan/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFelanmalanIdRoute =
  AuthenticatedAppFelanmalanIdRouteImport.update({
    id: '/felanmalan/$id',
    path: '/felanmalan/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boka-demo': typeof BokaDemoRoute
  '/priser': typeof PriserRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/entreprenor': typeof AuthenticatedEntreprenorRouteWithChildren
  '/auth/aterstall': typeof AuthAterstallRoute
  '/admin/abonnemang': typeof AuthenticatedAdminAbonnemangRoute
  '/admin/besiktningar': typeof AuthenticatedAdminBesiktningarRoute
  '/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/admin/dokument': typeof AuthenticatedAdminDokumentRoute
  '/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/admin/meddelanden': typeof AuthenticatedAdminMeddelandenRoute
  '/admin/moten': typeof AuthenticatedAdminMotenRoute
  '/admin/passersystem': typeof AuthenticatedAdminPassersystemRoute
  '/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/app/boende': typeof AuthenticatedAppBoendeRoute
  '/app/bokningar': typeof AuthenticatedAppBokningarRoute
  '/app/dokument': typeof AuthenticatedAppDokumentRoute
  '/app/ekonomi': typeof AuthenticatedAppEkonomiRoute
  '/app/information': typeof AuthenticatedAppInformationRoute
  '/app/meddelanden': typeof AuthenticatedAppMeddelandenRoute
  '/app/moten': typeof AuthenticatedAppMotenRoute
  '/app/nycklar': typeof AuthenticatedAppNycklarRoute
  '/entreprenor/$id': typeof AuthenticatedEntreprenorIdRoute
  '/n/$doorId': typeof AuthenticatedNDoorIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/entreprenor/': typeof AuthenticatedEntreprenorIndexRoute
  '/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
  '/app/felanmalan/$id': typeof AuthenticatedAppFelanmalanIdRoute
  '/admin/arenden/': typeof AuthenticatedAdminArendenIndexRoute
  '/admin/boende/': typeof AuthenticatedAdminBoendeIndexRoute
  '/app/felanmalan/': typeof AuthenticatedAppFelanmalanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/boka-demo': typeof BokaDemoRoute
  '/priser': typeof PriserRoute
  '/auth/aterstall': typeof AuthAterstallRoute
  '/admin/abonnemang': typeof AuthenticatedAdminAbonnemangRoute
  '/admin/besiktningar': typeof AuthenticatedAdminBesiktningarRoute
  '/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/admin/dokument': typeof AuthenticatedAdminDokumentRoute
  '/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/admin/meddelanden': typeof AuthenticatedAdminMeddelandenRoute
  '/admin/moten': typeof AuthenticatedAdminMotenRoute
  '/admin/passersystem': typeof AuthenticatedAdminPassersystemRoute
  '/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/app/boende': typeof AuthenticatedAppBoendeRoute
  '/app/bokningar': typeof AuthenticatedAppBokningarRoute
  '/app/dokument': typeof AuthenticatedAppDokumentRoute
  '/app/ekonomi': typeof AuthenticatedAppEkonomiRoute
  '/app/information': typeof AuthenticatedAppInformationRoute
  '/app/meddelanden': typeof AuthenticatedAppMeddelandenRoute
  '/app/moten': typeof AuthenticatedAppMotenRoute
  '/app/nycklar': typeof AuthenticatedAppNycklarRoute
  '/entreprenor/$id': typeof AuthenticatedEntreprenorIdRoute
  '/n/$doorId': typeof AuthenticatedNDoorIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/entreprenor': typeof AuthenticatedEntreprenorIndexRoute
  '/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
  '/app/felanmalan/$id': typeof AuthenticatedAppFelanmalanIdRoute
  '/admin/arenden': typeof AuthenticatedAdminArendenIndexRoute
  '/admin/boende': typeof AuthenticatedAdminBoendeIndexRoute
  '/app/felanmalan': typeof AuthenticatedAppFelanmalanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/boka-demo': typeof BokaDemoRoute
  '/priser': typeof PriserRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/entreprenor': typeof AuthenticatedEntreprenorRouteWithChildren
  '/auth_/aterstall': typeof AuthAterstallRoute
  '/_authenticated/admin/abonnemang': typeof AuthenticatedAdminAbonnemangRoute
  '/_authenticated/admin/besiktningar': typeof AuthenticatedAdminBesiktningarRoute
  '/_authenticated/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/_authenticated/admin/dokument': typeof AuthenticatedAdminDokumentRoute
  '/_authenticated/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/_authenticated/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/_authenticated/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/_authenticated/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/_authenticated/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/_authenticated/admin/meddelanden': typeof AuthenticatedAdminMeddelandenRoute
  '/_authenticated/admin/moten': typeof AuthenticatedAdminMotenRoute
  '/_authenticated/admin/passersystem': typeof AuthenticatedAdminPassersystemRoute
  '/_authenticated/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/_authenticated/app/boende': typeof AuthenticatedAppBoendeRoute
  '/_authenticated/app/bokningar': typeof AuthenticatedAppBokningarRoute
  '/_authenticated/app/dokument': typeof AuthenticatedAppDokumentRoute
  '/_authenticated/app/ekonomi': typeof AuthenticatedAppEkonomiRoute
  '/_authenticated/app/information': typeof AuthenticatedAppInformationRoute
  '/_authenticated/app/meddelanden': typeof AuthenticatedAppMeddelandenRoute
  '/_authenticated/app/moten': typeof AuthenticatedAppMotenRoute
  '/_authenticated/app/nycklar': typeof AuthenticatedAppNycklarRoute
  '/_authenticated/entreprenor/$id': typeof AuthenticatedEntreprenorIdRoute
  '/_authenticated/n/$doorId': typeof AuthenticatedNDoorIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/entreprenor/': typeof AuthenticatedEntreprenorIndexRoute
  '/_authenticated/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/_authenticated/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
  '/_authenticated/app/felanmalan/$id': typeof AuthenticatedAppFelanmalanIdRoute
  '/_authenticated/admin/arenden/': typeof AuthenticatedAdminArendenIndexRoute
  '/_authenticated/admin/boende/': typeof AuthenticatedAdminBoendeIndexRoute
  '/_authenticated/app/felanmalan/': typeof AuthenticatedAppFelanmalanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/boka-demo'
    | '/priser'
    | '/admin'
    | '/app'
    | '/entreprenor'
    | '/auth/aterstall'
    | '/admin/abonnemang'
    | '/admin/besiktningar'
    | '/admin/bokningar'
    | '/admin/dokument'
    | '/admin/ekonomi'
    | '/admin/entreprenorer'
    | '/admin/fastigheter'
    | '/admin/installningar'
    | '/admin/kommunikation'
    | '/admin/meddelanden'
    | '/admin/moten'
    | '/admin/passersystem'
    | '/admin/underhall'
    | '/app/boende'
    | '/app/bokningar'
    | '/app/dokument'
    | '/app/ekonomi'
    | '/app/information'
    | '/app/meddelanden'
    | '/app/moten'
    | '/app/nycklar'
    | '/entreprenor/$id'
    | '/n/$doorId'
    | '/api/stripe/webhook'
    | '/admin/'
    | '/app/'
    | '/entreprenor/'
    | '/admin/arenden/$id'
    | '/admin/boende/$id'
    | '/app/felanmalan/$id'
    | '/admin/arenden/'
    | '/admin/boende/'
    | '/app/felanmalan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/boka-demo'
    | '/priser'
    | '/auth/aterstall'
    | '/admin/abonnemang'
    | '/admin/besiktningar'
    | '/admin/bokningar'
    | '/admin/dokument'
    | '/admin/ekonomi'
    | '/admin/entreprenorer'
    | '/admin/fastigheter'
    | '/admin/installningar'
    | '/admin/kommunikation'
    | '/admin/meddelanden'
    | '/admin/moten'
    | '/admin/passersystem'
    | '/admin/underhall'
    | '/app/boende'
    | '/app/bokningar'
    | '/app/dokument'
    | '/app/ekonomi'
    | '/app/information'
    | '/app/meddelanden'
    | '/app/moten'
    | '/app/nycklar'
    | '/entreprenor/$id'
    | '/n/$doorId'
    | '/api/stripe/webhook'
    | '/admin'
    | '/app'
    | '/entreprenor'
    | '/admin/arenden/$id'
    | '/admin/boende/$id'
    | '/app/felanmalan/$id'
    | '/admin/arenden'
    | '/admin/boende'
    | '/app/felanmalan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/boka-demo'
    | '/priser'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/entreprenor'
    | '/auth_/aterstall'
    | '/_authenticated/admin/abonnemang'
    | '/_authenticated/admin/besiktningar'
    | '/_authenticated/admin/bokningar'
    | '/_authenticated/admin/dokument'
    | '/_authenticated/admin/ekonomi'
    | '/_authenticated/admin/entreprenorer'
    | '/_authenticated/admin/fastigheter'
    | '/_authenticated/admin/installningar'
    | '/_authenticated/admin/kommunikation'
    | '/_authenticated/admin/meddelanden'
    | '/_authenticated/admin/moten'
    | '/_authenticated/admin/passersystem'
    | '/_authenticated/admin/underhall'
    | '/_authenticated/app/boende'
    | '/_authenticated/app/bokningar'
    | '/_authenticated/app/dokument'
    | '/_authenticated/app/ekonomi'
    | '/_authenticated/app/information'
    | '/_authenticated/app/meddelanden'
    | '/_authenticated/app/moten'
    | '/_authenticated/app/nycklar'
    | '/_authenticated/entreprenor/$id'
    | '/_authenticated/n/$doorId'
    | '/api/stripe/webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/entreprenor/'
    | '/_authenticated/admin/arenden/$id'
    | '/_authenticated/admin/boende/$id'
    | '/_authenticated/app/felanmalan/$id'
    | '/_authenticated/admin/arenden/'
    | '/_authenticated/admin/boende/'
    | '/_authenticated/app/felanmalan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BokaDemoRoute: typeof BokaDemoRoute
  PriserRoute: typeof PriserRoute
  AuthAterstallRoute: typeof AuthAterstallRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boka-demo': {
      id: '/boka-demo'
      path: '/boka-demo'
      fullPath: '/boka-demo'
      preLoaderRoute: typeof BokaDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprenor': {
      id: '/_authenticated/entreprenor'
      path: '/entreprenor'
      fullPath: '/entreprenor'
      preLoaderRoute: typeof AuthenticatedEntreprenorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/aterstall': {
      id: '/auth_/aterstall'
      path: '/auth/aterstall'
      fullPath: '/auth/aterstall'
      preLoaderRoute: typeof AuthAterstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/abonnemang': {
      id: '/_authenticated/admin/abonnemang'
      path: '/abonnemang'
      fullPath: '/admin/abonnemang'
      preLoaderRoute: typeof AuthenticatedAdminAbonnemangRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/besiktningar': {
      id: '/_authenticated/admin/besiktningar'
      path: '/besiktningar'
      fullPath: '/admin/besiktningar'
      preLoaderRoute: typeof AuthenticatedAdminBesiktningarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bokningar': {
      id: '/_authenticated/admin/bokningar'
      path: '/bokningar'
      fullPath: '/admin/bokningar'
      preLoaderRoute: typeof AuthenticatedAdminBokningarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dokument': {
      id: '/_authenticated/admin/dokument'
      path: '/dokument'
      fullPath: '/admin/dokument'
      preLoaderRoute: typeof AuthenticatedAdminDokumentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ekonomi': {
      id: '/_authenticated/admin/ekonomi'
      path: '/ekonomi'
      fullPath: '/admin/ekonomi'
      preLoaderRoute: typeof AuthenticatedAdminEkonomiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/entreprenorer': {
      id: '/_authenticated/admin/entreprenorer'
      path: '/entreprenorer'
      fullPath: '/admin/entreprenorer'
      preLoaderRoute: typeof AuthenticatedAdminEntreprenorerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fastigheter': {
      id: '/_authenticated/admin/fastigheter'
      path: '/fastigheter'
      fullPath: '/admin/fastigheter'
      preLoaderRoute: typeof AuthenticatedAdminFastigheterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/installningar': {
      id: '/_authenticated/admin/installningar'
      path: '/installningar'
      fullPath: '/admin/installningar'
      preLoaderRoute: typeof AuthenticatedAdminInstallningarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kommunikation': {
      id: '/_authenticated/admin/kommunikation'
      path: '/kommunikation'
      fullPath: '/admin/kommunikation'
      preLoaderRoute: typeof AuthenticatedAdminKommunikationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/meddelanden': {
      id: '/_authenticated/admin/meddelanden'
      path: '/meddelanden'
      fullPath: '/admin/meddelanden'
      preLoaderRoute: typeof AuthenticatedAdminMeddelandenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moten': {
      id: '/_authenticated/admin/moten'
      path: '/moten'
      fullPath: '/admin/moten'
      preLoaderRoute: typeof AuthenticatedAdminMotenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/passersystem': {
      id: '/_authenticated/admin/passersystem'
      path: '/passersystem'
      fullPath: '/admin/passersystem'
      preLoaderRoute: typeof AuthenticatedAdminPassersystemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/underhall': {
      id: '/_authenticated/admin/underhall'
      path: '/underhall'
      fullPath: '/admin/underhall'
      preLoaderRoute: typeof AuthenticatedAdminUnderhallRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/boende': {
      id: '/_authenticated/app/boende'
      path: '/boende'
      fullPath: '/app/boende'
      preLoaderRoute: typeof AuthenticatedAppBoendeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bokningar': {
      id: '/_authenticated/app/bokningar'
      path: '/bokningar'
      fullPath: '/app/bokningar'
      preLoaderRoute: typeof AuthenticatedAppBokningarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dokument': {
      id: '/_authenticated/app/dokument'
      path: '/dokument'
      fullPath: '/app/dokument'
      preLoaderRoute: typeof AuthenticatedAppDokumentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ekonomi': {
      id: '/_authenticated/app/ekonomi'
      path: '/ekonomi'
      fullPath: '/app/ekonomi'
      preLoaderRoute: typeof AuthenticatedAppEkonomiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/information': {
      id: '/_authenticated/app/information'
      path: '/information'
      fullPath: '/app/information'
      preLoaderRoute: typeof AuthenticatedAppInformationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/meddelanden': {
      id: '/_authenticated/app/meddelanden'
      path: '/meddelanden'
      fullPath: '/app/meddelanden'
      preLoaderRoute: typeof AuthenticatedAppMeddelandenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/moten': {
      id: '/_authenticated/app/moten'
      path: '/moten'
      fullPath: '/app/moten'
      preLoaderRoute: typeof AuthenticatedAppMotenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nycklar': {
      id: '/_authenticated/app/nycklar'
      path: '/nycklar'
      fullPath: '/app/nycklar'
      preLoaderRoute: typeof AuthenticatedAppNycklarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/entreprenor/': {
      id: '/_authenticated/entreprenor/'
      path: '/'
      fullPath: '/entreprenor/'
      preLoaderRoute: typeof AuthenticatedEntreprenorIndexRouteImport
      parentRoute: typeof AuthenticatedEntreprenorRoute
    }
    '/_authenticated/entreprenor/$id': {
      id: '/_authenticated/entreprenor/$id'
      path: '/$id'
      fullPath: '/entreprenor/$id'
      preLoaderRoute: typeof AuthenticatedEntreprenorIdRouteImport
      parentRoute: typeof AuthenticatedEntreprenorRoute
    }
    '/_authenticated/n/$doorId': {
      id: '/_authenticated/n/$doorId'
      path: '/n/$doorId'
      fullPath: '/n/$doorId'
      preLoaderRoute: typeof AuthenticatedNDoorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/arenden/': {
      id: '/_authenticated/admin/arenden/'
      path: '/arenden'
      fullPath: '/admin/arenden/'
      preLoaderRoute: typeof AuthenticatedAdminArendenIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/arenden/$id': {
      id: '/_authenticated/admin/arenden/$id'
      path: '/arenden/$id'
      fullPath: '/admin/arenden/$id'
      preLoaderRoute: typeof AuthenticatedAdminArendenIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/boende/': {
      id: '/_authenticated/admin/boende/'
      path: '/boende'
      fullPath: '/admin/boende/'
      preLoaderRoute: typeof AuthenticatedAdminBoendeIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/boende/$id': {
      id: '/_authenticated/admin/boende/$id'
      path: '/boende/$id'
      fullPath: '/admin/boende/$id'
      preLoaderRoute: typeof AuthenticatedAdminBoendeIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/felanmalan/': {
      id: '/_authenticated/app/felanmalan/'
      path: '/felanmalan'
      fullPath: '/app/felanmalan/'
      preLoaderRoute: typeof AuthenticatedAppFelanmalanIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/felanmalan/$id': {
      id: '/_authenticated/app/felanmalan/$id'
      path: '/felanmalan/$id'
      fullPath: '/app/felanmalan/$id'
      preLoaderRoute: typeof AuthenticatedAppFelanmalanIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAbonnemangRoute: typeof AuthenticatedAdminAbonnemangRoute
  AuthenticatedAdminBesiktningarRoute: typeof AuthenticatedAdminBesiktningarRoute
  AuthenticatedAdminBokningarRoute: typeof AuthenticatedAdminBokningarRoute
  AuthenticatedAdminDokumentRoute: typeof AuthenticatedAdminDokumentRoute
  AuthenticatedAdminEkonomiRoute: typeof AuthenticatedAdminEkonomiRoute
  AuthenticatedAdminEntreprenorerRoute: typeof AuthenticatedAdminEntreprenorerRoute
  AuthenticatedAdminFastigheterRoute: typeof AuthenticatedAdminFastigheterRoute
  AuthenticatedAdminInstallningarRoute: typeof AuthenticatedAdminInstallningarRoute
  AuthenticatedAdminKommunikationRoute: typeof AuthenticatedAdminKommunikationRoute
  AuthenticatedAdminMeddelandenRoute: typeof AuthenticatedAdminMeddelandenRoute
  AuthenticatedAdminMotenRoute: typeof AuthenticatedAdminMotenRoute
  AuthenticatedAdminPassersystemRoute: typeof AuthenticatedAdminPassersystemRoute
  AuthenticatedAdminUnderhallRoute: typeof AuthenticatedAdminUnderhallRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminArendenIdRoute: typeof AuthenticatedAdminArendenIdRoute
  AuthenticatedAdminBoendeIdRoute: typeof AuthenticatedAdminBoendeIdRoute
  AuthenticatedAdminArendenIndexRoute: typeof AuthenticatedAdminArendenIndexRoute
  AuthenticatedAdminBoendeIndexRoute: typeof AuthenticatedAdminBoendeIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAbonnemangRoute: AuthenticatedAdminAbonnemangRoute,
  AuthenticatedAdminBesiktningarRoute: AuthenticatedAdminBesiktningarRoute,
  AuthenticatedAdminBokningarRoute: AuthenticatedAdminBokningarRoute,
  AuthenticatedAdminDokumentRoute: AuthenticatedAdminDokumentRoute,
  AuthenticatedAdminEkonomiRoute: AuthenticatedAdminEkonomiRoute,
  AuthenticatedAdminEntreprenorerRoute: AuthenticatedAdminEntreprenorerRoute,
  AuthenticatedAdminFastigheterRoute: AuthenticatedAdminFastigheterRoute,
  AuthenticatedAdminInstallningarRoute: AuthenticatedAdminInstallningarRoute,
  AuthenticatedAdminKommunikationRoute: AuthenticatedAdminKommunikationRoute,
  AuthenticatedAdminMeddelandenRoute: AuthenticatedAdminMeddelandenRoute,
  AuthenticatedAdminMotenRoute: AuthenticatedAdminMotenRoute,
  AuthenticatedAdminPassersystemRoute: AuthenticatedAdminPassersystemRoute,
  AuthenticatedAdminUnderhallRoute: AuthenticatedAdminUnderhallRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminArendenIdRoute: AuthenticatedAdminArendenIdRoute,
  AuthenticatedAdminBoendeIdRoute: AuthenticatedAdminBoendeIdRoute,
  AuthenticatedAdminArendenIndexRoute: AuthenticatedAdminArendenIndexRoute,
  AuthenticatedAdminBoendeIndexRoute: AuthenticatedAdminBoendeIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBoendeRoute: typeof AuthenticatedAppBoendeRoute
  AuthenticatedAppBokningarRoute: typeof AuthenticatedAppBokningarRoute
  AuthenticatedAppDokumentRoute: typeof AuthenticatedAppDokumentRoute
  AuthenticatedAppEkonomiRoute: typeof AuthenticatedAppEkonomiRoute
  AuthenticatedAppInformationRoute: typeof AuthenticatedAppInformationRoute
  AuthenticatedAppMeddelandenRoute: typeof AuthenticatedAppMeddelandenRoute
  AuthenticatedAppMotenRoute: typeof AuthenticatedAppMotenRoute
  AuthenticatedAppNycklarRoute: typeof AuthenticatedAppNycklarRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppFelanmalanIdRoute: typeof AuthenticatedAppFelanmalanIdRoute
  AuthenticatedAppFelanmalanIndexRoute: typeof AuthenticatedAppFelanmalanIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBoendeRoute: AuthenticatedAppBoendeRoute,
  AuthenticatedAppBokningarRoute: AuthenticatedAppBokningarRoute,
  AuthenticatedAppDokumentRoute: AuthenticatedAppDokumentRoute,
  AuthenticatedAppEkonomiRoute: AuthenticatedAppEkonomiRoute,
  AuthenticatedAppInformationRoute: AuthenticatedAppInformationRoute,
  AuthenticatedAppMeddelandenRoute: AuthenticatedAppMeddelandenRoute,
  AuthenticatedAppMotenRoute: AuthenticatedAppMotenRoute,
  AuthenticatedAppNycklarRoute: AuthenticatedAppNycklarRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppFelanmalanIdRoute: AuthenticatedAppFelanmalanIdRoute,
  AuthenticatedAppFelanmalanIndexRoute: AuthenticatedAppFelanmalanIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedEntreprenorRouteChildren {
  AuthenticatedEntreprenorIdRoute: typeof AuthenticatedEntreprenorIdRoute
  AuthenticatedEntreprenorIndexRoute: typeof AuthenticatedEntreprenorIndexRoute
}

const AuthenticatedEntreprenorRouteChildren: AuthenticatedEntreprenorRouteChildren =
  {
    AuthenticatedEntreprenorIdRoute: AuthenticatedEntreprenorIdRoute,
    AuthenticatedEntreprenorIndexRoute: AuthenticatedEntreprenorIndexRoute,
  }

const AuthenticatedEntreprenorRouteWithChildren =
  AuthenticatedEntreprenorRoute._addFileChildren(
    AuthenticatedEntreprenorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedEntreprenorRoute: typeof AuthenticatedEntreprenorRouteWithChildren
  AuthenticatedNDoorIdRoute: typeof AuthenticatedNDoorIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedEntreprenorRoute: AuthenticatedEntreprenorRouteWithChildren,
  AuthenticatedNDoorIdRoute: AuthenticatedNDoorIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BokaDemoRoute: BokaDemoRoute,
  PriserRoute: PriserRoute,
  AuthAterstallRoute: AuthAterstallRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
