/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminArendenRouteImport } from './routes/_authenticated/admin.arenden'
import { Route as AuthenticatedAdminBoendeRouteImport } from './routes/_authenticated/admin.boende'
import { Route as AuthenticatedAdminBokningarRouteImport } from './routes/_authenticated/admin.bokningar'
import { Route as AuthenticatedAdminEkonomiRouteImport } from './routes/_authenticated/admin.ekonomi'
import { Route as AuthenticatedAdminEntreprenorerRouteImport } from './routes/_authenticated/admin.entreprenorer'
import { Route as AuthenticatedAdminFastigheterRouteImport } from './routes/_authenticated/admin.fastigheter'
import { Route as AuthenticatedAdminInstallningarRouteImport } from './routes/_authenticated/admin.installningar'
import { Route as AuthenticatedAdminKommunikationRouteImport } from './routes/_authenticated/admin.kommunikation'
import { Route as AuthenticatedAdminUnderhallRouteImport } from './routes/_authenticated/admin.underhall'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminArendenIdRouteImport } from './routes/_authenticated/admin.arenden.$id'
import { Route as AuthenticatedAdminBoendeIdRouteImport } from './routes/_authenticated/admin.boende.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminArendenRoute =
  AuthenticatedAdminArendenRouteImport.update({
    id: '/arenden',
    path: '/arenden',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBoendeRoute =
  AuthenticatedAdminBoendeRouteImport.update({
    id: '/boende',
    path: '/boende',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBokningarRoute =
  AuthenticatedAdminBokningarRouteImport.update({
    id: '/bokningar',
    path: '/bokningar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEkonomiRoute =
  AuthenticatedAdminEkonomiRouteImport.update({
    id: '/ekonomi',
    path: '/ekonomi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEntreprenorerRoute =
  AuthenticatedAdminEntreprenorerRouteImport.update({
    id: '/entreprenorer',
    path: '/entreprenorer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFastigheterRoute =
  AuthenticatedAdminFastigheterRouteImport.update({
    id: '/fastigheter',
    path: '/fastigheter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstallningarRoute =
  AuthenticatedAdminInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKommunikationRoute =
  AuthenticatedAdminKommunikationRouteImport.update({
    id: '/kommunikation',
    path: '/kommunikation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUnderhallRoute =
  AuthenticatedAdminUnderhallRouteImport.update({
    id: '/underhall',
    path: '/underhall',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminArendenIdRoute =
  AuthenticatedAdminArendenIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminArendenRoute,
  } as any)
const AuthenticatedAdminBoendeIdRoute =
  AuthenticatedAdminBoendeIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBoendeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/admin/arenden': typeof AuthenticatedAdminArendenRouteWithChildren
  '/admin/boende': typeof AuthenticatedAdminBoendeRouteWithChildren
  '/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/arenden': typeof AuthenticatedAdminArendenRouteWithChildren
  '/admin/boende': typeof AuthenticatedAdminBoendeRouteWithChildren
  '/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/admin/arenden': typeof AuthenticatedAdminArendenRouteWithChildren
  '/_authenticated/admin/boende': typeof AuthenticatedAdminBoendeRouteWithChildren
  '/_authenticated/admin/bokningar': typeof AuthenticatedAdminBokningarRoute
  '/_authenticated/admin/ekonomi': typeof AuthenticatedAdminEkonomiRoute
  '/_authenticated/admin/entreprenorer': typeof AuthenticatedAdminEntreprenorerRoute
  '/_authenticated/admin/fastigheter': typeof AuthenticatedAdminFastigheterRoute
  '/_authenticated/admin/installningar': typeof AuthenticatedAdminInstallningarRoute
  '/_authenticated/admin/kommunikation': typeof AuthenticatedAdminKommunikationRoute
  '/_authenticated/admin/underhall': typeof AuthenticatedAdminUnderhallRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/arenden/$id': typeof AuthenticatedAdminArendenIdRoute
  '/_authenticated/admin/boende/$id': typeof AuthenticatedAdminBoendeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/admin/arenden'
    | '/admin/boende'
    | '/admin/bokningar'
    | '/admin/ekonomi'
    | '/admin/entreprenorer'
    | '/admin/fastigheter'
    | '/admin/installningar'
    | '/admin/kommunikation'
    | '/admin/underhall'
    | '/admin/'
    | '/app/'
    | '/admin/arenden/$id'
    | '/admin/boende/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/arenden'
    | '/admin/boende'
    | '/admin/bokningar'
    | '/admin/ekonomi'
    | '/admin/entreprenorer'
    | '/admin/fastigheter'
    | '/admin/installningar'
    | '/admin/kommunikation'
    | '/admin/underhall'
    | '/admin'
    | '/app'
    | '/admin/arenden/$id'
    | '/admin/boende/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/admin/arenden'
    | '/_authenticated/admin/boende'
    | '/_authenticated/admin/bokningar'
    | '/_authenticated/admin/ekonomi'
    | '/_authenticated/admin/entreprenorer'
    | '/_authenticated/admin/fastigheter'
    | '/_authenticated/admin/installningar'
    | '/_authenticated/admin/kommunikation'
    | '/_authenticated/admin/underhall'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/arenden/$id'
    | '/_authenticated/admin/boende/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/arenden': {
      id: '/_authenticated/admin/arenden'
      path: '/arenden'
      fullPath: '/admin/arenden'
      preLoaderRoute: typeof AuthenticatedAdminArendenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/boende': {
      id: '/_authenticated/admin/boende'
      path: '/boende'
      fullPath: '/admin/boende'
      preLoaderRoute: typeof AuthenticatedAdminBoendeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bokningar': {
      id: '/_authenticated/admin/bokningar'
      path: '/bokningar'
      fullPath: '/admin/bokningar'
      preLoaderRoute: typeof AuthenticatedAdminBokningarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ekonomi': {
      id: '/_authenticated/admin/ekonomi'
      path: '/ekonomi'
      fullPath: '/admin/ekonomi'
      preLoaderRoute: typeof AuthenticatedAdminEkonomiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/entreprenorer': {
      id: '/_authenticated/admin/entreprenorer'
      path: '/entreprenorer'
      fullPath: '/admin/entreprenorer'
      preLoaderRoute: typeof AuthenticatedAdminEntreprenorerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fastigheter': {
      id: '/_authenticated/admin/fastigheter'
      path: '/fastigheter'
      fullPath: '/admin/fastigheter'
      preLoaderRoute: typeof AuthenticatedAdminFastigheterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/installningar': {
      id: '/_authenticated/admin/installningar'
      path: '/installningar'
      fullPath: '/admin/installningar'
      preLoaderRoute: typeof AuthenticatedAdminInstallningarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kommunikation': {
      id: '/_authenticated/admin/kommunikation'
      path: '/kommunikation'
      fullPath: '/admin/kommunikation'
      preLoaderRoute: typeof AuthenticatedAdminKommunikationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/underhall': {
      id: '/_authenticated/admin/underhall'
      path: '/underhall'
      fullPath: '/admin/underhall'
      preLoaderRoute: typeof AuthenticatedAdminUnderhallRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/arenden/$id': {
      id: '/_authenticated/admin/arenden/$id'
      path: '/$id'
      fullPath: '/admin/arenden/$id'
      preLoaderRoute: typeof AuthenticatedAdminArendenIdRouteImport
      parentRoute: typeof AuthenticatedAdminArendenRoute
    }
    '/_authenticated/admin/boende/$id': {
      id: '/_authenticated/admin/boende/$id'
      path: '/$id'
      fullPath: '/admin/boende/$id'
      preLoaderRoute: typeof AuthenticatedAdminBoendeIdRouteImport
      parentRoute: typeof AuthenticatedAdminBoendeRoute
    }
  }
}

interface AuthenticatedAdminArendenRouteChildren {
  AuthenticatedAdminArendenIdRoute: typeof AuthenticatedAdminArendenIdRoute
}

const AuthenticatedAdminArendenRouteChildren: AuthenticatedAdminArendenRouteChildren =
  {
    AuthenticatedAdminArendenIdRoute: AuthenticatedAdminArendenIdRoute,
  }

const AuthenticatedAdminArendenRouteWithChildren =
  AuthenticatedAdminArendenRoute._addFileChildren(
    AuthenticatedAdminArendenRouteChildren,
  )

interface AuthenticatedAdminBoendeRouteChildren {
  AuthenticatedAdminBoendeIdRoute: typeof AuthenticatedAdminBoendeIdRoute
}

const AuthenticatedAdminBoendeRouteChildren: AuthenticatedAdminBoendeRouteChildren =
  {
    AuthenticatedAdminBoendeIdRoute: AuthenticatedAdminBoendeIdRoute,
  }

const AuthenticatedAdminBoendeRouteWithChildren =
  AuthenticatedAdminBoendeRoute._addFileChildren(
    AuthenticatedAdminBoendeRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminArendenRoute: typeof AuthenticatedAdminArendenRouteWithChildren
  AuthenticatedAdminBoendeRoute: typeof AuthenticatedAdminBoendeRouteWithChildren
  AuthenticatedAdminBokningarRoute: typeof AuthenticatedAdminBokningarRoute
  AuthenticatedAdminEkonomiRoute: typeof AuthenticatedAdminEkonomiRoute
  AuthenticatedAdminEntreprenorerRoute: typeof AuthenticatedAdminEntreprenorerRoute
  AuthenticatedAdminFastigheterRoute: typeof AuthenticatedAdminFastigheterRoute
  AuthenticatedAdminInstallningarRoute: typeof AuthenticatedAdminInstallningarRoute
  AuthenticatedAdminKommunikationRoute: typeof AuthenticatedAdminKommunikationRoute
  AuthenticatedAdminUnderhallRoute: typeof AuthenticatedAdminUnderhallRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminArendenRoute: AuthenticatedAdminArendenRouteWithChildren,
  AuthenticatedAdminBoendeRoute: AuthenticatedAdminBoendeRouteWithChildren,
  AuthenticatedAdminBokningarRoute: AuthenticatedAdminBokningarRoute,
  AuthenticatedAdminEkonomiRoute: AuthenticatedAdminEkonomiRoute,
  AuthenticatedAdminEntreprenorerRoute: AuthenticatedAdminEntreprenorerRoute,
  AuthenticatedAdminFastigheterRoute: AuthenticatedAdminFastigheterRoute,
  AuthenticatedAdminInstallningarRoute: AuthenticatedAdminInstallningarRoute,
  AuthenticatedAdminKommunikationRoute: AuthenticatedAdminKommunikationRoute,
  AuthenticatedAdminUnderhallRoute: AuthenticatedAdminUnderhallRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
